### ISSUE TITLE
Support for ESP32

### ISSUE THREAD

**Issue by achton** [craftyguy/esp-bootstrap#4]
I have purchased a WEMOS LOLIN32 **ESP32** module, and would like to run esp-bootstrap on it. This issue is just for tracking issues that I have come across. I am running off custom built firmware in the micropython-esp32 repo.

**uhashlib is called hashlib:**
```
diff --git a/main.py b/main.py
index 6a96ab5..ad2a8f3 100644
--- a/main.py
+++ b/main.py
@@ -7,7 +7,10 @@ import config
 import os
 import secrets
 import socket
-import uhashlib
+try:
+    import hashlib as uhashlib
+except ImportError:
+    import uhashlib
 import utime
 
 ###### Constants ######
```

**esp.osdebug() does not exist**
Needs to be checked in code

**socket implementation differs**

It seems the esp8266 firmware is built on lwip for sockets, and esp32 is not. Thus, `sock.setsockopt()` takes a different final argument, apparently, resulting in this error:
```
I (158533) modsocket: Initializing
Traceback (most recent call last):
  File "boot.py", line 33, in <module>
  File "main.py", line 96, in <module>
TypeError: can't convert function to int
```

**Comment by craftyguy** [comment]
Oh, interesting, thank you for doing this! I haven't had an excuse to get an ESP32 yet.. I was kind of hoping that micropython would be more portable than you suggest.. maybe it's just a matter of time. If not, we may have to go the classic #IFDEF route (or whatever Python's equivalent is) for specific device support. That's less desirable for obvious reasons!

**Comment by craftyguy** [comment]
@achton 
Just curious if you've found anything else when running this on the esp32? I'm going to try to get one of these in the next few months and apply any necessary updates to this project to get it running.

**Comment by achton** [comment]
@craftyguy I've actually not been doing anything with my ESP32 since I posted this issue, so don't have anything to contribute. I'd like to help out with any specifics though, so let me know if you find anything that needs fixing :-)

**Comment by craftyguy** [comment]
@achton no problem. I have an esp32 on order now and will let you know if there's anything I need help with, thanks for the offer :)
